//
//  Database.swift
//  Eckstein
//
//  This file would normally be generated by: supabase gen types swift
//  For now, we'll define the types manually
//

import Foundation

// MARK: - Database Types

struct UserPreferences: Codable {
    let id: UUID
    let userId: UUID
    let dailyCalorieGoal: Int
    let dailyProteinGoal: Int
    let dailyCarbGoal: Int
    let weightUnit: String
    let heightCm: Int?
    let activityLevel: String
    let createdAt: Date
    let updatedAt: Date
    
    enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case dailyCalorieGoal = "daily_calorie_goal"
        case dailyProteinGoal = "daily_protein_goal"
        case dailyCarbGoal = "daily_carb_goal"
        case weightUnit = "weight_unit"
        case heightCm = "height_cm"
        case activityLevel = "activity_level"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}

struct Exercise: Codable {
    let id: UUID
    let name: String
    let category: String
    let muscleGroup: String?
    let equipment: String?
    let isCustom: Bool
    let createdBy: UUID?
    let createdAt: Date
    
    enum CodingKeys: String, CodingKey {
        case id, name, category
        case muscleGroup = "muscle_group"
        case equipment
        case isCustom = "is_custom"
        case createdBy = "created_by"
        case createdAt = "created_at"
    }
}

struct Workout: Codable {
    let id: UUID
    let userId: UUID
    let name: String
    let date: Date
    let durationMinutes: Int?
    let notes: String?
    let completed: Bool
    let createdAt: Date
    let updatedAt: Date
    
    enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case name, date
        case durationMinutes = "duration_minutes"
        case notes, completed
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}

struct WorkoutSet: Codable {
    let id: UUID
    let workoutId: UUID
    let exerciseId: UUID
    let setNumber: Int
    let weightKg: Double?
    let reps: Int?
    let completed: Bool
    let notes: String?
    let createdAt: Date
    
    enum CodingKeys: String, CodingKey {
        case id
        case workoutId = "workout_id"
        case exerciseId = "exercise_id"
        case setNumber = "set_number"
        case weightKg = "weight_kg"
        case reps, completed, notes
        case createdAt = "created_at"
    }
}

struct Food: Codable {
    let id: UUID
    let name: String
    let brand: String?
    let barcode: String?
    let caloriesPer100g: Int
    let proteinPer100g: Double
    let carbsPer100g: Double
    let fatPer100g: Double
    let isCustom: Bool
    let createdBy: UUID?
    let createdAt: Date
    
    enum CodingKeys: String, CodingKey {
        case id, name, brand, barcode
        case caloriesPer100g = "calories_per_100g"
        case proteinPer100g = "protein_per_100g"
        case carbsPer100g = "carbs_per_100g"
        case fatPer100g = "fat_per_100g"
        case isCustom = "is_custom"
        case createdBy = "created_by"
        case createdAt = "created_at"
    }
}